version: '3'
services:
  picker:
    container_name: hp
    image: hymns-picker:0.6.0
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - kibana
  es:
    container_name: es
    image: elasticsearch:8.4.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - discovery.type=single-node
    volumes:
      - ~/hymns-data/elasticsearch-data/data:/usr/share/elasticsearch/data
      - ~/hymns-data/elasticsearch-data/plugins:/usr/share/elasticsearch/plugins
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
  kibana:
    container_name: kibana
    image: kibana:8.4.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: '["http://es:9200"]'
      SERVER_SSL_ENABLED: "false"
    volumes:
      - ~/hymns-data/kibana-data/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: unless-stopped
    depends_on:
      - es