version: '3'
services:
  picker:
    container_name: hp
    image: hymns-picker
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - label-studio
      - digger
  digger:
    container_name: hd
    image: hymns-digger
    ports:
      - "8082:8082"
    environment:
      ELASTIC_SEARCH_HOST_AND_PORT: ${ELASTIC_SEARCH_HOST_AND_PORT}
    restart: unless-stopped
    depends_on:
      - es
      - kibana
  label-studio:
    container_name: ls
    image: heartexlabs/label-studio
    ports:
      - "8080:8080"
    volumes:
      - ~/IdeaProjects/hymns-data/label-studio-data:/label-studio/data
    restart: unless-stopped
  es:
    container_name: es
    image: elasticsearch:8.4.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    volumes:
      - ~/IdeaProjects/hymns-data/elasticsearch-data/data:/usr/share/elasticsearch/data
      - ~/IdeaProjects/hymns-data/elasticsearch-data/plugins:/usr/share/elasticsearch/plugins
      - ~/IdeaProjects/hymns-data/elasticsearch-data/config:/usr/share/elasticsearch/config
    restart: unless-stopped
  kibana:
    container_name: kibana
    image: kibana:8.4.3
    ports:
      - "5601:5601"
    volumes:
      - ~/IdeaProjects/hymns-data/kibana-data/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: unless-stopped

